### PR TITLE
Create Stronghold2b.java

### PR DESCRIPTION
**Pull request by EBSmash**
I just saw the 9b one and had made this a while back. think it would make a good addition to the client.

### CODE REVIEW

**Comment by anOtherAnalyse** [comment]
Sure that would be of use. Do you think you could make a few adjustments before merging ?
- You could merge your code into the existing command & use Minecraft.getCurrentServerData() to check the current server and return the appropriate coords for 9b or 2b.
- Use the method player.getDistanceSq() to compute square distance, no need to rewrite existing code
- start the loop counter (i.e i) at 1 since index 0 is the nearest by default, and remove the System.out.println(): no need to pollute the logs

Thank you.

**Comment by EBSmash** [comment]
Ill work on it!

**Comment by EBSmash** [comment]
Alright I think this is good. let me know if i should change anything. (Sorry i took so long)

**Comment by EBSmash** [comment]
Alright I think this is good. let me know if i should change anything. (Sorry i took so long)

**Comment by anOtherAnalyse** [comment]
Looking good, thanks for the contribution !

**Pull request merged**
